# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loggui_complete.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Log_screen(object):
    def setupUi(self, Log_screen):
        Log_screen.setObjectName("Log_screen")
        Log_screen.resize(450, 550)
        self.centralwidget = QtWidgets.QWidget(Log_screen)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 30, 370, 480))
        self.widget.setStyleSheet("QPushButton#button_login{\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#button_login:hover{\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(40,67,98,219), stop:1 rgba(105,118,132,226));\n"
"}\n"
"QPushButton#button_login:pressed{\n"
"    padding-left:5px;\n"
"    padding-stop:5px;\n"
"    background-color: rgba(105,118,132,200);\n"
"}\n"
"QPushButton#button_cancer{\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#button_cancer:hover{\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(40,67,98,219), stop:1 rgba(105,118,132,226));\n"
"}\n"
"QPushButton#button_cancer:pressed{\n"
"    padding-left:5px;\n"
"    padding-stop:5px;\n"
"    background-color: rgba(105,118,132,200);\n"
"}\n"
"QPushButton#button_show:pressed{\n"
"    padding-left:5px;\n"
"    padding-stop:5px;\n"
"    background-color: rgba(105,118,132,200);\n"
"}\n"
"QPushButton#button_pass:pressed{\n"
"    padding-left:5px;\n"
"    padding-stop:5px;\n"
"    background-color: rgba(105,118,132,200);\n"
"}\n"
"QPushButton#button_error{\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#button_error:hover{\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(40,67,98,219), stop:1 rgba(105,118,132,226));\n"
"}\n"
"QPushButton#button_erroe:pressed{\n"
"    padding-left:5px;\n"
"    padding-stop:5px;\n"
"    background-color: rgba(105,118,132,200);\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(30, 30, 300, 420))
        self.label.setStyleSheet("border-image: url(:/images/background.png);\n"
"border-radius:20px;\n"
"\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 280, 390))
        self.label_2.setStyleSheet("background-color: rgba(0,0,0,100);\n"
"border-radius:20px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(135, 95, 101, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgba(255,255,255,210);\n"
"")
        self.label_6.setScaledContents(False)
        self.label_6.setObjectName("label_6")
        self.screen_user = QtWidgets.QLineEdit(self.widget)
        self.screen_user.setGeometry(QtCore.QRect(80, 165, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.screen_user.setFont(font)
        self.screen_user.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border : none;\n"
"border-bottom: 2px solid rgba(10,118,132,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom : 7px;")
        self.screen_user.setObjectName("screen_user")
        self.screen_pass = QtWidgets.QLineEdit(self.widget)
        self.screen_pass.setGeometry(QtCore.QRect(80, 230, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.screen_pass.setFont(font)
        self.screen_pass.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border : none;\n"
"border-bottom: 2px solid rgba(10,118,132,255);\n"
"color: rgba(255,255,255,230);\n"
"padding-bottom : 7px;")
        self.screen_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.screen_pass.setObjectName("screen_pass")
        self.button_login = QtWidgets.QPushButton(self.widget)
        self.button_login.setGeometry(QtCore.QRect(80, 280, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_login.setFont(font)
        self.button_login.setObjectName("button_login")
        self.button_cancer = QtWidgets.QPushButton(self.widget)
        self.button_cancer.setGeometry(QtCore.QRect(80, 330, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_cancer.setFont(font)
        self.button_cancer.setObjectName("button_cancer")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(90, 380, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 85, 127);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(220, 430, 91, 16))
        self.label_8.setStyleSheet("color:rgba(255,255,255,140);")
        self.label_8.setObjectName("label_8")
        self.button_show = QtWidgets.QPushButton(self.widget)
        self.button_show.setGeometry(QtCore.QRect(260, 240, 51, 28))
        self.button_show.setAutoFillBackground(False)
        self.button_show.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgba(255, 255,255,0);")
        self.button_show.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("eye (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_show.setIcon(icon)
        self.button_show.setObjectName("button_show")
        self.button_pass = QtWidgets.QPushButton(self.widget)
        self.button_pass.setGeometry(QtCore.QRect(260, 240, 51, 28))
        self.button_pass.setAutoFillBackground(False)
        self.button_pass.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgba(255, 255,255,0);")
        self.button_pass.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("eye-crossed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_pass.setIcon(icon1)
        self.button_pass.setObjectName("button_pass")
        self.button_error = QtWidgets.QPushButton(self.widget)
        self.button_error.setGeometry(QtCore.QRect(80, 280, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_error.setFont(font)
        self.button_error.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.button_error.setObjectName("button_error")
        self.label.raise_()
        self.label_2.raise_()
        self.label_6.raise_()
        self.screen_user.raise_()
        self.screen_pass.raise_()
        self.button_cancer.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.button_show.raise_()
        self.button_pass.raise_()
        self.button_error.raise_()
        self.button_login.raise_()
        Log_screen.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Log_screen)
        self.statusbar.setObjectName("statusbar")
        Log_screen.setStatusBar(self.statusbar)

        self.retranslateUi(Log_screen)
        QtCore.QMetaObject.connectSlotsByName(Log_screen)

    def retranslateUi(self, Log_screen):
        _translate = QtCore.QCoreApplication.translate
        Log_screen.setWindowTitle(_translate("Log_screen", "MainWindow"))
        self.label_6.setText(_translate("Log_screen", "Log in"))
        self.screen_user.setPlaceholderText(_translate("Log_screen", " User Name"))
        self.screen_pass.setPlaceholderText(_translate("Log_screen", " Password"))
        self.button_login.setText(_translate("Log_screen", "L O G  I N"))
        self.button_cancer.setText(_translate("Log_screen", "C A N C E R"))
        self.label_7.setText(_translate("Log_screen", "MAGICIAN ROBOT"))
        self.label_8.setText(_translate("Log_screen", "Creted by Thắng"))
        self.button_error.setText(_translate("Log_screen", "A G A I N"))
import icon_rc
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Log_screen = QtWidgets.QMainWindow()
    ui = Ui_Log_screen()
    ui.setupUi(Log_screen)
    Log_screen.show()
    sys.exit(app.exec_())
